name: giphy_get_demo
description: giphy_get Demo APP.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_dotenv: ^5.0.2
  flutter:
    sdk: flutter
  giphy_get:
    path: ../

  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env
