name: giphy_get
description: Pick EMOJI,STICKER or GIF from Giphy in pure dart code. Support Android,iOS,Web and Desktop.
version: 0.9.4
homepage: https://github.com/bazospa/giphy_get


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2
  extended_image: ^1.1.2
  flutter_staggered_grid_view: ^0.3.2
  meta: ^1.1.8
  http: ^0.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  coverage: ^0.13.0
  pedantic: ^1.4.0
  matcher: 

flutter:
  assets:
    - assets/img/
